import { Geist, Geist_Mono, Great_Vibes } from "next/font/google";
import "./globals.css";
import { FavoritesProvider } from "./context/FavoritesContext";
import { BookingsProvider } from "./context/BookingsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  variable: "--font-cario-heading",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Cario | Book your route for best Travels Experience",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${greatVibes.variable} antialiased`}
      >
        <FavoritesProvider>
          <BookingsProvider>
            {children}
          </BookingsProvider>
        </FavoritesProvider>
      </body>
    </html>
  );
}
